### ISSUE TITLE
Navegacion y lambdas

### ISSUE THREAD

**Issue by josemontecastelo** [drg471/RustAndRevolt#3]
https://github.com/drg471/RustAndRevolt/blob/26d895a93f40761b060d09962dbf63494b977d17/app/src/main/java/com/drg/rustandrevolt/navigation/AppNavigation.kt#L19C1-L20C1

Como lo has hecho está bien y es correcto, pero suele hacerse de la siguiente manera

```
            HomeScreen(
                navigateToOptionsScreen = {
                    navController.navigate(AppScreens.OptionsScreen.route)
                },
                navigateToSelectCharacterScreen = {
                    navController.navigate(AppScreens.SelectCharacterScreen.route)
                }
            )

```

Con esto te evitas tener que declarar las variables.

**Comment by drg471** [comment]
Vale, lo voy a dejar así porque las lambdas no las controlo mucho y por el momento lo leo mejor como está. Seguro que practicando más y en poco tiempo lo veo totalmente innecesario.
